- README.md
- public/css/custom.css
- public/css/layout.css
- public/tpl/header.html
- public/views/home.html
Optimied the frontpage CSS so it looks more clean and elements like scrollbars look similar to the theme.
Also updated README to show that this is indeed a ETC Explorer, not ETH
> Optimize frontpage CSS

- public/js/controllers/AddressController.js
etherunits.js corrects the addr.balance from wei to normal units and limits decimal places
> add unit conversion

- public/js/stats/The_bomb_chart_with_ECIP_1010.js
- public/js/stats/bundle_The_bomb_chart_with_ECIP_1010.js
> bomb chart update , v0.2

- views/index.ejs
> Update http to https

- db.js
- tools/internals.js
- tools/stats.js
This was needed for my docker setup, currently overwriting the file with COPY.
This might be useful for other people as well, hope it helps
> add MONGO_URI env variable to mongoose.connect

- public/tpl/header.html
added dropdown with links to:
tokenmint
CEW
etcstats
statebot
morden stats
> community dropdown

- .gitignore
- package.json
set external dep for web3 and solc
ref: issue #64
> fix package.json

- public/js/controllers/HomeController.js
- public/views/home.html
- public/views/simple-summary-stats.html
- public/views/site-notes.html
- routes/stats.js
- extract siteNotes as a directive and support simpleSummaryStats directive.
(screen shot with a different blockchain)
> simple summary stats

- public/tpl/footer.html
http://www.ethereumclassic.com is a broken link
> fixed broken link

- public/views/block.html
- public/views/tx.html
* show block prev / next links, like as https://etherscan.io or etherchain-light
* show numbers using the number filter (tx.html)
* hide "Transactions" table header when transactions.length == 0 (omitted in the commit log)
> show block prev / next links

- routes/web3relay.js
- tools/stats.js
- `tools/config.json` has been renamed `config.json`
- `db-stats.js` has been already merged into `db.js`
- fixup `web3relay.js` as intended
> update for recent change

- config.json
- tools/sync.js
Changed typo from *==* to *<=* in getOldestBlockDB() function
> syncAll typo fix

- public/js/controllers/AddressController.js
- public/views/address.html
- routes/index.js
- show mined counter using `Block.aggregate()`
- get transaction counter and fix `recordsTotal` using `Transaction.aggregate()`
See also #108
> show all transactions, mined counter

- public/js/controllers/AddressController.js
- routes/index.js
support DataTable sorting.
- blockNumber or date fields have same meaning.
- disable sort by tx.value. (tx.value is a string)
> enable sort by tx.blockNumber

- config.json
- public/js/main.js
- public/tpl/footer.html
- public/tpl/header.html
- public/views/err_404.html
- views/index.ejs
more configurable settings added.
~~~.js
"contact": "mailto:elaine.ou@gmail.com",
"about": "This is an open source Blockchain Explorer.",
"rss": "http://ethereumclassic.org",
"reddit": "https://www.reddit.com/r/EthereumClassic",
"twitter": "https://twitter.com/ethereumclassic",
"linkedin": "https://www.linkedin.com/company/ethereum-classic",
"github": "https://github.com/ethereumproject",
"logo": "/img/explorer-logo.png",
"customCss": "green-haze.min.css",
"copyright": "2018 &copy; Ethereum Classic."
~~~
Please see also #87
> more configurable settings

- public/views/home.html
- routes/index.js
set transaction counter using `Transaction.aggregate()`
(regression by 0ea56f8d09705 commit.)
> show transaction counter correctly

- tools/patcher.js
`tools/patcher.js` is just a `patchBlocks()` version of the original `tools/grabber.js`.
(`tools/blockHelper.js` is also just a `grabBlocks()` version of the original `tools/grabber.js`)
------
you can check it with following instruction.
- original `tools/grabber.js` : `git show cf02b74 -- tools/grabber.js >orig.js`
- `tools/patcher.js` : `git show a35bdd2 -- tools/patcher.js >new .js`
- `diff -ubw orig.js new.js`
~~~.diff
slightly fixed hunks
diff -ubw orig-grabber.js new-patcher.js
@@ -10,43 +16,12 @@
var Block     = mongoose.model( 'Block' );
var Transaction     = mongoose.model( 'Transaction' );
-var grabBlocks = function(config) {
-    var web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:' +
-        config.gethPort.toString()));
-
-
-    if('listenOnly' in config …
> tools/patcher.js: fixed to make it work as intended

- config.json
- public/js/controllers/AddressController.js
- public/views/address.html
`settings.useEthFiat` option added to enable/disable `ethFiat` feature in the address page.
the `ethFiat` feature use external api (http://api.blockcypher.com ) and sometime it cause crash.
> settings.useEthFiat option added

- public/js/controllers/StatsController.js
- public/tpl/header.html
- public/views/stats/index.html
> support blocktime/difficulty chart

- config.json
Changed the Addresses from MiningPoolHub and 2miners.
Added Whalesburg Miner Address.
> Updated Addresses

- db.js
> fixed mongoose deprecation warning

- db.js
- lib/trace.js
- public/js/controllers/AccountsController.js
- public/js/main.js
- public/tpl/header.html
- public/views/accounts.html
- routes/index.js
- routes/richlist.js
- routes/web3relay.js
- tools/richlist.js
- tools/sync.js
***ready to merge***
Support Rich List ~~using the parity extension.~~
- Token balance not supported.
- `$ time node tools/richlist.js` for EthersocialNetwork (ESN) - about ~~40~~ 8 min with the parity extension.
- bulk insert supported. (default `100` items)
- ~~this is the only parity extension dependent part.~~
- about ~~100~~ ~20 min without the parity extension(`--fat-db=on`).
> support Rich List

- public/tpl/header.html
cleanup `href="javascript:;"`.
it makes some troubles on safari/iPhone.
> cleanup href="javascript:;" links

- config.example.json
- package.json
- public/tpl/footer.html
- public/tpl/header.html
#192 
Rename to ethereumclassic
> Rename to ethereumclassic

- public/js/filters.js
- public/views/block.html
+ Added extra unit calculation
> Fix block total difficulty
